sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: development
  
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then haxelib run travix python; fi
  - haxelib run travix node
  - haxelib run travix php
  - haxelib run travix js
  - haxelib run travix java -D static_target
  - haxelib run travix cpp -D static_target -lib hxcpp
  - haxelib run travix cs -D static_target
