# The first thing is to tell which VM environment we want the test to be run on.
# It dosen't quite matter for Haxe, just choose one of the targets our project support (e.g. PHP),
# and than apt-get install the others (e.g. Neko, C++).
# For more info, see http://about.travis-ci.org/docs/user/ci-environment/
language: node_js

env:
    matrix:
    - TARGET=cpp
    - TARGET=cs
    - TARGET=java
    - TARGET=js
    - TARGET=neko
    - TARGET=nodejs
    - TARGET=php
    - TARGET=flash
    - TARGET=python

before_install:
  # Install Haxe
  - wget http://www.openfl.org/builds/haxe/haxe-3.2.1-linux-installer.tar.gz -O - | tar -xv
  - sudo sh install-haxe.sh -y

  # haxelib dependencies for all targets
  - haxelib install HaxeContracts
  - haxelib install buddy

  # apt packages for each target
  - sudo apt-get update
  - sh -c "if [ '$TARGET' = 'cpp' ]; then sudo apt-get install gcc-multilib g++-multilib -y; fi"
  - sh -c "if [ '$TARGET' = 'cs' ]; then sudo apt-get install mono-devel -y; fi"
  - sh -c "if [ '$TARGET' = 'js' ]; then sudo apt-get install phantomjs -y; fi"
  - sh -c "if [ '$TARGET' = 'php' ]; then sudo apt-get install php5-cli -y; fi"
  - sh -c "if [ '$TARGET' = 'flash' ]; then chmod +x ./flash-travis-setup.sh && ./flash-travis-setup.sh; fi"
  - sh -c "if [ '$TARGET' = 'python' ]; then sudo apt-get install python3 -y; fi"

  # haxelib dependencies for each target
  - sh -c "if [ '$TARGET' = 'cpp' ]; then haxelib install hxcpp; fi"
  - sh -c "if [ '$TARGET' = 'java' ]; then haxelib install hxjava; fi"
  - sh -c "if [ '$TARGET' = 'cs' ]; then haxelib install hxcs; fi"

# Run the test!
script:
  - haxe tests.hxml
  - neko bin/neko.n
  - node bin/nodejs.js
  # -phantomjs
  #.- ./.travis-phantomjs-script.sh phantomjs.js '0 failures'
  - java -jar bin/Tests.jar
  - php bin/index.php
  - mono bin/bin/Tests.exe
  - ./.travis-flash-script.sh bin/flash.swf
  - ./bin/Tests
  - python3 bin/python.py

  - haxe -dce full tests.hxml
  - neko bin/neko.n
  - node bin/nodejs.js
  # -phantomjs
  #.- ./.travis-phantomjs-script.sh phantomjs.js '0 failures'
  - java -jar bin/Tests.jar
  - php bin/index.php
  - mono bin/bin/Tests.exe
  - ./.travis-flash-script.sh bin/flash.swf
  - ./bin/Tests
  - python3 bin/python.py

branches:
      only:
          - master