sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - development
  
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix php
  - haxelib run travix js
  - haxelib run travix flash -D static
  - haxelib run travix java -D static
  - haxelib run travix cpp -D static -lib hxcpp
  - haxelib run travix cs -D static
